# Generated by Django 3.1 on 2020-08-21 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DAILY_HIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PHISHING', models.IntegerField(blank=True, null=True)),
                ('DAY_HITS', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NEW_URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.TextField(blank=True)),
                ('HITS', models.IntegerField(blank=True, default=0, null=True)),
                ('DAILY_HITS', models.IntegerField(blank=True, default=0, null=True)),
                ('DATE', models.DateTimeField(auto_now=True)),
                ('LABEL', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ORIGINAL_URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.TextField(blank=True)),
                ('DATE', models.DateTimeField(auto_now=True)),
                ('HITS', models.IntegerField(blank=True, default=0, null=True)),
                ('DAILY_HITS', models.IntegerField(blank=True, default=0, null=True)),
                ('LABEL', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
